language: python
python:
    - "3.3"
    - "2.7"
      # command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
      #
before_install:
    - sudo apt-get update
    - sudo apt-get install python-opencv
    - sudo dpkg -L python-opencv
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda
install:

    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
      # we use conda to prevent compiling big packages
    - conda install --yes numpy scipy astropy ephem numexpr scikit-image pillow matplotlib basemap docutils pip
      # # OpenCV only supports Python 3 in the new 3.0 version (to be released)
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
      conda install --yes opencv ;
      fi
      # - travis_retry pip install -r dev-requirements.txt
    - pip install -r requirements.txt
    - pip install pytest
    - pip install pylint
script:
    - py.test
    - pylint -E protolab/
