language: python
python:
    - "3.3"
    - "2.7"
      # command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
      #
before_install:
    - sudo apt-get update
    - sudo apt-get install python-opencv
    - sudo dpkg -L python-opencv
install:
    - pip install -r requirements.txt
    - pip install pytest
    - pip install pylint
script:
    - py.test
    - pylint -E protolab/
