language: python
python:
    - "3.3"
    - "2.7"
      # command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install pytest
    - pip install pylint
script:
    - py.test
    - pylint -E protolab/
